### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by maxinatorixx** [ipiv/webrtc-screenshare#5]
Can you tell me how to set this up on windows step for step? I have absolutely no idea how this works. Ive got a xampp installation and a nodejs installation ready and want to host everything including the signalhub server by myself

**Comment by ipiv** [comment]
This example is just a static website that you can host wherever. 
For setting up Signalhub I suggest checking out [Signalhub repository](https://github.com/mafintosh/signalhub)
